### ISSUE TITLE
Pages aren't counted properly in bills

### ISSUE THREAD

**Issue by aph3rson** [emipa606/RimWriter#2]
When pages are produced, something seems to prevent bills from determining the right count of existing pages available.

For example:

- Bill configured to make until 2, only sees 1 after making a stack of 100.
  ![image](https://user-images.githubusercontent.com/838916/151725059-aeee00fe-61f4-4c20-8597-5ff469c822be.png)
- Bill configured to make until 2, sees 3 after another stack is made + prexisting stack is split.  
  ![image](https://user-images.githubusercontent.com/838916/151725105-2b04d9a1-6042-4305-b970-14c494127a3d.png)

It appears that bills are only able to count distinct stacks of paper, rather than the paper itself...?
(No other bills act like this, so it's something with Pages themselves.)

**Comment by emipa606** [comment]
Should be fixed in 06b5847
Thanks for the report!
