### ISSUE TITLE
[Bug] Books within bookshelves uncountable by bills

### ISSUE THREAD

**Issue by aph3rson** [emipa606/RimWriter#3]
If a bill is configured to limit the number of books to be produced (e.g. to the space available nearby), books stored in bookshelves are not counted within the bill.

For example - here's a typewriter table which is configured to produce up-to 16 books.

![image](https://user-images.githubusercontent.com/838916/151914816-5c25cf7a-05ac-454e-83a5-344e2f363a24.png)

However, it's unable to count books in the nearby bookshelf:

![image](https://user-images.githubusercontent.com/838916/151914883-37757635-3a69-4b21-b6d1-a47d8565fdca.png)

However, it is able to count books if they're on the ground (dropped via the Retrieve Book gizmo):

![image](https://user-images.githubusercontent.com/838916/151914920-5f494085-5916-4623-af68-63374b11ae5d.png)

Is it possible that the `Building_InnerStorage` mechanic is preventing the bill from finding resources in this storage? It seems to work for books in storage items like PRF's industrial crates (which work by stacking many items in a single cell).

**Comment by emipa606** [comment]
Not really possible since stored books technically doesnt exist. PRFs items still exist, just are placed on top of eachother so the mapLister can still enumerate them.
